# Generated by Django 6.0.4 on 2026-05-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrainComUaProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('memory', models.CharField(blank=True, max_length=100, null=True)),
                ('price_regular', models.CharField(blank=True, max_length=50, null=True)),
                ('price_sale', models.CharField(blank=True, max_length=50, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('reviews_count', models.IntegerField(blank=True, null=True)),
                ('screen_diagonal', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=100, null=True)),
                ('characteristics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Brain Product',
                'verbose_name_plural': 'Brain Products',
            },
        ),
    ]
